package com.briup.apps.zhaopin.bean;

public class Business {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.contact_name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.contact_phone
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.industry
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String industry;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.location
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String location;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.scale
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String scale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.established_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String establishedTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.registered_capital
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String registeredCapital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.description
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.business_license
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String businessLicense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_business.city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String city;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.id
     *
     * @return the value of zp_business.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.id
     *
     * @param id the value for zp_business.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.name
     *
     * @return the value of zp_business.name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.name
     *
     * @param name the value for zp_business.name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.contact_name
     *
     * @return the value of zp_business.contact_name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.contact_name
     *
     * @param contactName the value for zp_business.contact_name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.contact_phone
     *
     * @return the value of zp_business.contact_phone
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.contact_phone
     *
     * @param contactPhone the value for zp_business.contact_phone
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.industry
     *
     * @return the value of zp_business.industry
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getIndustry() {
        return industry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.industry
     *
     * @param industry the value for zp_business.industry
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setIndustry(String industry) {
        this.industry = industry == null ? null : industry.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.location
     *
     * @return the value of zp_business.location
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.location
     *
     * @param location the value for zp_business.location
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.scale
     *
     * @return the value of zp_business.scale
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getScale() {
        return scale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.scale
     *
     * @param scale the value for zp_business.scale
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setScale(String scale) {
        this.scale = scale == null ? null : scale.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.established_time
     *
     * @return the value of zp_business.established_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getEstablishedTime() {
        return establishedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.established_time
     *
     * @param establishedTime the value for zp_business.established_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setEstablishedTime(String establishedTime) {
        this.establishedTime = establishedTime == null ? null : establishedTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.registered_capital
     *
     * @return the value of zp_business.registered_capital
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getRegisteredCapital() {
        return registeredCapital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.registered_capital
     *
     * @param registeredCapital the value for zp_business.registered_capital
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setRegisteredCapital(String registeredCapital) {
        this.registeredCapital = registeredCapital == null ? null : registeredCapital.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.description
     *
     * @return the value of zp_business.description
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.description
     *
     * @param description the value for zp_business.description
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.business_license
     *
     * @return the value of zp_business.business_license
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getBusinessLicense() {
        return businessLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.business_license
     *
     * @param businessLicense the value for zp_business.business_license
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setBusinessLicense(String businessLicense) {
        this.businessLicense = businessLicense == null ? null : businessLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.status
     *
     * @return the value of zp_business.status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.status
     *
     * @param status the value for zp_business.status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.province
     *
     * @return the value of zp_business.province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.province
     *
     * @param province the value for zp_business.province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_business.city
     *
     * @return the value of zp_business.city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_business.city
     *
     * @param city the value for zp_business.city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }
}