package com.briup.apps.zhaopin.bean;

import java.util.Date;

public class Employment {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.title
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.contact_name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String contactName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.contact_phone
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String contactPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.job
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.publish_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String welfare;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.salary
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.description
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.num
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.business_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long businessId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.working_hours
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String workingHours;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.job_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.start_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Date startTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.end_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Date endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment.audit_status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String auditStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.id
     *
     * @return the value of zp_employment.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.id
     *
     * @param id the value for zp_employment.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.title
     *
     * @return the value of zp_employment.title
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.title
     *
     * @param title the value for zp_employment.title
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.contact_name
     *
     * @return the value of zp_employment.contact_name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getContactName() {
        return contactName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.contact_name
     *
     * @param contactName the value for zp_employment.contact_name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setContactName(String contactName) {
        this.contactName = contactName == null ? null : contactName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.contact_phone
     *
     * @return the value of zp_employment.contact_phone
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.contact_phone
     *
     * @param contactPhone the value for zp_employment.contact_phone
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone == null ? null : contactPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.job
     *
     * @return the value of zp_employment.job
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.job
     *
     * @param job the value for zp_employment.job
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.publish_time
     *
     * @return the value of zp_employment.publish_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.publish_time
     *
     * @param publishTime the value for zp_employment.publish_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.welfare
     *
     * @return the value of zp_employment.welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getWelfare() {
        return welfare;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.welfare
     *
     * @param welfare the value for zp_employment.welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setWelfare(String welfare) {
        this.welfare = welfare == null ? null : welfare.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.salary
     *
     * @return the value of zp_employment.salary
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.salary
     *
     * @param salary the value for zp_employment.salary
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setSalary(String salary) {
        this.salary = salary == null ? null : salary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.description
     *
     * @return the value of zp_employment.description
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.description
     *
     * @param description the value for zp_employment.description
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.status
     *
     * @return the value of zp_employment.status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.status
     *
     * @param status the value for zp_employment.status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.num
     *
     * @return the value of zp_employment.num
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.num
     *
     * @param num the value for zp_employment.num
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.business_id
     *
     * @return the value of zp_employment.business_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getBusinessId() {
        return businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.business_id
     *
     * @param businessId the value for zp_employment.business_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setBusinessId(Long businessId) {
        this.businessId = businessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.working_hours
     *
     * @return the value of zp_employment.working_hours
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getWorkingHours() {
        return workingHours;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.working_hours
     *
     * @param workingHours the value for zp_employment.working_hours
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setWorkingHours(String workingHours) {
        this.workingHours = workingHours == null ? null : workingHours.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.job_id
     *
     * @return the value of zp_employment.job_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.job_id
     *
     * @param jobId the value for zp_employment.job_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.city
     *
     * @return the value of zp_employment.city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.city
     *
     * @param city the value for zp_employment.city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.province
     *
     * @return the value of zp_employment.province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.province
     *
     * @param province the value for zp_employment.province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.start_time
     *
     * @return the value of zp_employment.start_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Date getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.start_time
     *
     * @param startTime the value for zp_employment.start_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.end_time
     *
     * @return the value of zp_employment.end_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.end_time
     *
     * @param endTime the value for zp_employment.end_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment.audit_status
     *
     * @return the value of zp_employment.audit_status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment.audit_status
     *
     * @param auditStatus the value for zp_employment.audit_status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus == null ? null : auditStatus.trim();
    }
}