package com.briup.apps.zhaopin.bean;

import java.util.Date;

public class EmploymentJobhunter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment_jobhunter.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment_jobhunter.ask_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Date askTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment_jobhunter.remark
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment_jobhunter.employment_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long employmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_employment_jobhunter.jobhunter_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long jobhunterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment_jobhunter.id
     *
     * @return the value of zp_employment_jobhunter.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment_jobhunter.id
     *
     * @param id the value for zp_employment_jobhunter.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment_jobhunter.ask_time
     *
     * @return the value of zp_employment_jobhunter.ask_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Date getAskTime() {
        return askTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment_jobhunter.ask_time
     *
     * @param askTime the value for zp_employment_jobhunter.ask_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setAskTime(Date askTime) {
        this.askTime = askTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment_jobhunter.remark
     *
     * @return the value of zp_employment_jobhunter.remark
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment_jobhunter.remark
     *
     * @param remark the value for zp_employment_jobhunter.remark
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment_jobhunter.employment_id
     *
     * @return the value of zp_employment_jobhunter.employment_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getEmploymentId() {
        return employmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment_jobhunter.employment_id
     *
     * @param employmentId the value for zp_employment_jobhunter.employment_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setEmploymentId(Long employmentId) {
        this.employmentId = employmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_employment_jobhunter.jobhunter_id
     *
     * @return the value of zp_employment_jobhunter.jobhunter_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getJobhunterId() {
        return jobhunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_employment_jobhunter.jobhunter_id
     *
     * @param jobhunterId the value for zp_employment_jobhunter.jobhunter_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setJobhunterId(Long jobhunterId) {
        this.jobhunterId = jobhunterId;
    }
}