package com.briup.apps.zhaopin.bean;

public class Jobhunter {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.username
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.password
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.realname
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String realname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.gender
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.birth
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.telephone
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.education
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.work_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String workTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.current_status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String currentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter.resume
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String resume;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.id
     *
     * @return the value of zp_jobhunter.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.id
     *
     * @param id the value for zp_jobhunter.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.username
     *
     * @return the value of zp_jobhunter.username
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.username
     *
     * @param username the value for zp_jobhunter.username
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.password
     *
     * @return the value of zp_jobhunter.password
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.password
     *
     * @param password the value for zp_jobhunter.password
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.realname
     *
     * @return the value of zp_jobhunter.realname
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.realname
     *
     * @param realname the value for zp_jobhunter.realname
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setRealname(String realname) {
        this.realname = realname == null ? null : realname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.gender
     *
     * @return the value of zp_jobhunter.gender
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.gender
     *
     * @param gender the value for zp_jobhunter.gender
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.birth
     *
     * @return the value of zp_jobhunter.birth
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.birth
     *
     * @param birth the value for zp_jobhunter.birth
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.telephone
     *
     * @return the value of zp_jobhunter.telephone
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.telephone
     *
     * @param telephone the value for zp_jobhunter.telephone
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone == null ? null : telephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.education
     *
     * @return the value of zp_jobhunter.education
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.education
     *
     * @param education the value for zp_jobhunter.education
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.work_time
     *
     * @return the value of zp_jobhunter.work_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getWorkTime() {
        return workTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.work_time
     *
     * @param workTime the value for zp_jobhunter.work_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setWorkTime(String workTime) {
        this.workTime = workTime == null ? null : workTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.current_status
     *
     * @return the value of zp_jobhunter.current_status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getCurrentStatus() {
        return currentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.current_status
     *
     * @param currentStatus the value for zp_jobhunter.current_status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus == null ? null : currentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter.resume
     *
     * @return the value of zp_jobhunter.resume
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter.resume
     *
     * @param resume the value for zp_jobhunter.resume
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }
}