package com.briup.apps.zhaopin.bean;

public class JobhunterService {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter_service.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter_service.customer_service_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long customerServiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobhunter_service.employment_jobhunter_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long employmentJobhunterId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter_service.id
     *
     * @return the value of zp_jobhunter_service.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter_service.id
     *
     * @param id the value for zp_jobhunter_service.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter_service.customer_service_id
     *
     * @return the value of zp_jobhunter_service.customer_service_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getCustomerServiceId() {
        return customerServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter_service.customer_service_id
     *
     * @param customerServiceId the value for zp_jobhunter_service.customer_service_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setCustomerServiceId(Long customerServiceId) {
        this.customerServiceId = customerServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobhunter_service.employment_jobhunter_id
     *
     * @return the value of zp_jobhunter_service.employment_jobhunter_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getEmploymentJobhunterId() {
        return employmentJobhunterId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobhunter_service.employment_jobhunter_id
     *
     * @param employmentJobhunterId the value for zp_jobhunter_service.employment_jobhunter_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setEmploymentJobhunterId(Long employmentJobhunterId) {
        this.employmentJobhunterId = employmentJobhunterId;
    }
}