package com.briup.apps.zhaopin.bean;

public class Jobs {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobs.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobs.job_type_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long jobTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobs.name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_jobs.status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobs.id
     *
     * @return the value of zp_jobs.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobs.id
     *
     * @param id the value for zp_jobs.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobs.job_type_id
     *
     * @return the value of zp_jobs.job_type_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getJobTypeId() {
        return jobTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobs.job_type_id
     *
     * @param jobTypeId the value for zp_jobs.job_type_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setJobTypeId(Long jobTypeId) {
        this.jobTypeId = jobTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobs.name
     *
     * @return the value of zp_jobs.name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobs.name
     *
     * @param name the value for zp_jobs.name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_jobs.status
     *
     * @return the value of zp_jobs.status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_jobs.status
     *
     * @param status the value for zp_jobs.status
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }
}