package com.briup.apps.zhaopin.bean;

import java.util.Date;

public class Message {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_message.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_message.content
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_message.publish_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Date publishTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_message.zp_jobhunter_service_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long zpJobhunterServiceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_message.id
     *
     * @return the value of zp_message.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_message.id
     *
     * @param id the value for zp_message.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_message.content
     *
     * @return the value of zp_message.content
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_message.content
     *
     * @param content the value for zp_message.content
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_message.publish_time
     *
     * @return the value of zp_message.publish_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Date getPublishTime() {
        return publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_message.publish_time
     *
     * @param publishTime the value for zp_message.publish_time
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setPublishTime(Date publishTime) {
        this.publishTime = publishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_message.zp_jobhunter_service_id
     *
     * @return the value of zp_message.zp_jobhunter_service_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getZpJobhunterServiceId() {
        return zpJobhunterServiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_message.zp_jobhunter_service_id
     *
     * @param zpJobhunterServiceId the value for zp_message.zp_jobhunter_service_id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setZpJobhunterServiceId(Long zpJobhunterServiceId) {
        this.zpJobhunterServiceId = zpJobhunterServiceId;
    }
}