package com.briup.apps.zhaopin.bean;

public class Province {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_province.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zp_province.name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_province.id
     *
     * @return the value of zp_province.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_province.id
     *
     * @param id the value for zp_province.id
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zp_province.name
     *
     * @return the value of zp_province.name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zp_province.name
     *
     * @param name the value for zp_province.name
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}