package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.Browse;
import com.briup.apps.zhaopin.bean.BrowseExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BrowseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    long countByExample(BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int deleteByExample(BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int insert(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int insertSelective(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    List<Browse> selectByExample(BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    Browse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Browse record, @Param("example") BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int updateByExample(@Param("record") Browse record, @Param("example") BrowseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int updateByPrimaryKeySelective(Browse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_browse
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int updateByPrimaryKey(Browse record);
}