package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.Business;
import com.briup.apps.zhaopin.bean.BusinessExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface BusinessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<Business> selectByExample(BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    Business selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Business record, @Param("example") BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") Business record, @Param("example") BusinessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(Business record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_business
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(Business record);
}