package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.City;
import com.briup.apps.zhaopin.bean.CityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<City> selectByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    City selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_city
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(City record);
}