package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.Collect;
import com.briup.apps.zhaopin.bean.CollectExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CollectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    long countByExample(CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int deleteByExample(CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int insert(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int insertSelective(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    List<Collect> selectByExample(CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    Collect selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int updateByExampleSelective(@Param("record") Collect record, @Param("example") CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int updateByExample(@Param("record") Collect record, @Param("example") CollectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int updateByPrimaryKeySelective(Collect record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_collect
     *
     * @mbg.generated Fri Sep 27 11:17:20 CST 2019
     */
    int updateByPrimaryKey(Collect record);
}