package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.CustomerService;
import com.briup.apps.zhaopin.bean.CustomerServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(CustomerServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(CustomerServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(CustomerService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(CustomerService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<CustomerService> selectByExample(CustomerServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    CustomerService selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") CustomerService record, @Param("example") CustomerServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") CustomerService record, @Param("example") CustomerServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(CustomerService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_customer_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(CustomerService record);
}