package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.Employment;
import com.briup.apps.zhaopin.bean.EmploymentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmploymentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<Employment> selectByExample(EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    Employment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Employment record, @Param("example") EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") Employment record, @Param("example") EmploymentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(Employment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(Employment record);
}