package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.EmploymentJobhunter;
import com.briup.apps.zhaopin.bean.EmploymentJobhunterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EmploymentJobhunterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(EmploymentJobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(EmploymentJobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(EmploymentJobhunter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(EmploymentJobhunter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<EmploymentJobhunter> selectByExample(EmploymentJobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    EmploymentJobhunter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") EmploymentJobhunter record, @Param("example") EmploymentJobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") EmploymentJobhunter record, @Param("example") EmploymentJobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(EmploymentJobhunter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_employment_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(EmploymentJobhunter record);
}