package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.JobhunterService;
import com.briup.apps.zhaopin.bean.JobhunterServiceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobhunterServiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(JobhunterServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(JobhunterServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(JobhunterService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(JobhunterService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<JobhunterService> selectByExample(JobhunterServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    JobhunterService selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") JobhunterService record, @Param("example") JobhunterServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") JobhunterService record, @Param("example") JobhunterServiceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(JobhunterService record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter_service
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(JobhunterService record);
}