package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.Jobhunter;
import com.briup.apps.zhaopin.bean.JobhunterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobhunterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(JobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(JobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(Jobhunter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(Jobhunter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<Jobhunter> selectByExample(JobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    Jobhunter selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Jobhunter record, @Param("example") JobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") Jobhunter record, @Param("example") JobhunterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(Jobhunter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobhunter
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(Jobhunter record);
}