package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.Jobs;
import com.briup.apps.zhaopin.bean.JobsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(Jobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(Jobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<Jobs> selectByExample(JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    Jobs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Jobs record, @Param("example") JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") Jobs record, @Param("example") JobsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(Jobs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_jobs
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(Jobs record);
}