package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.JobType;
import com.briup.apps.zhaopin.bean.JobTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JobTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(JobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(JobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<JobType> selectByExample(JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    JobType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") JobType record, @Param("example") JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") JobType record, @Param("example") JobTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(JobType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_job_type
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(JobType record);
}