package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.Province;
import com.briup.apps.zhaopin.bean.ProvinceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ProvinceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<Province> selectByExample(ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    Province selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") Province record, @Param("example") ProvinceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(Province record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_province
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(Province record);
}