package com.briup.apps.zhaopin.mapper;

import com.briup.apps.zhaopin.bean.Welfare;
import com.briup.apps.zhaopin.bean.WelfareExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WelfareMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    long countByExample(WelfareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByExample(WelfareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insert(Welfare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int insertSelective(Welfare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    List<Welfare> selectByExample(WelfareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    Welfare selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExampleSelective(@Param("record") Welfare record, @Param("example") WelfareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByExample(@Param("record") Welfare record, @Param("example") WelfareExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKeySelective(Welfare record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zp_welfare
     *
     * @mbg.generated Thu Dec 12 19:18:16 CST 2019
     */
    int updateByPrimaryKey(Welfare record);
}